"""Unit tests: the alert rules cover the thresholds the docs promise.

Why this is a test rather than a comment
----------------------------------------
`docs/launch-checklist-and-runbook.md` opens with a rule that is currently
unenforced: *"清单里的每一条阈值都必须有一个对应的门禁或指标——写在这里
却没有门禁的项，视为未实现"*. A threshold written in a runbook with no alert
attached is a wish. Prometheus does not complain about a rule that never fires,
a rule that references a metric nobody exports, or a rule whose expression has
a typo in a label; it simply sits there looking configured. So each property
below is asserted against the parsed rules and the real metric registry.

The metric names are read from `render_metrics()` - the exact bytes Prometheus
scrapes - rather than from the source or from `registry.collect()`. The latter
returns the *undecorated* name (`platform_agent_runs`, not
`platform_agent_runs_total`), so validating a rule against it would accept a
rule that can never match. Exposition names are the contract.

`promtool check rules` is not available here and would not be better: it
validates PromQL syntax, which is not the failure mode. A syntactically valid
expression naming a metric this application never exports is the common case,
and only a test that knows the registry catches it.
"""

from __future__ import annotations

import pathlib
import re
from typing import Any

import pytest
import yaml

REPO_ROOT = pathlib.Path(__file__).resolve().parents[4]
K8S = REPO_ROOT / "infra" / "kubernetes"

# PromQL function calls, aggregation keywords and Prometheus' own builtin
# series. `up` is generated by the scrape machinery, not exported by this
# application, so it is the one identifier that legitimately has no
# counterpart in the registry.
_PROMQL_NOISE = frozenset(
    {
        "by",
        "without",
        "on",
        "ignoring",
        "group_left",
        "group_right",
        "bool",
        "sum",
        "rate",
        "increase",
        "avg",
        "min",
        "max",
        "count",
        "and",
        "or",
        "unless",
        "offset",
        "up",
    }
)
_SELECTOR = re.compile(r"([a-zA-Z_:][a-zA-Z0-9_:]*)\s*(?:\{|\[)")


def _rule_documents() -> list[dict[str, Any]]:
    return _documents_of_kind("PrometheusRule")


def _service_monitors() -> list[dict[str, Any]]:
    return _documents_of_kind("ServiceMonitor")


def _documents_of_kind(kind: str) -> list[dict[str, Any]]:
    docs: list[dict[str, Any]] = []
    for path in sorted(K8S.glob("*.yaml")):
        if path.name.endswith(".example.yaml") or path.name == "kustomization.yaml":
            continue
        for doc in yaml.safe_load_all(path.read_text(encoding="utf-8")):
            if doc and doc.get("kind") == kind:
                docs.append(doc)
    return docs


def _all_rules() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for doc in _rule_documents():
        for group in doc["spec"]["groups"]:
            out.extend(group["rules"])
    return out


def _exposition_metric_names() -> set[str]:
    from observability_metrics import render_metrics

    text = render_metrics().decode("utf-8")
    return {line.split()[2] for line in text.splitlines() if line.startswith("# TYPE")}


def _referenced_metrics(expr: str) -> set[str]:
    return {name for name in _SELECTOR.findall(expr) if name not in _PROMQL_NOISE}


# --- the rules exist at all --------------------------------------------------


def test_alert_rules_are_declared_in_the_manifests() -> None:
    """A repository with 39 exported metric families and no alert rules is the
    state this was written to end. `PrometheusRule` is the standard CRD, so it
    is used rather than a bespoke ConfigMap of PromQL."""
    assert _rule_documents(), (
        "no PrometheusRule in infra/kubernetes: every threshold in "
        "docs/launch-checklist-and-runbook.md is unenforced until one is"
    )


def test_the_rules_are_part_of_the_kustomization() -> None:
    """A manifest in the directory that `kubectl apply -k` does not reference
    is a manifest that never reaches the cluster - the same trap
    `11-secret.example.yaml` is called out for, in the other direction."""
    kustomization = (K8S / "kustomization.yaml").read_text(encoding="utf-8")
    listed = {
        line.strip().lstrip("-").strip()
        for line in kustomization.splitlines()
        if line.strip().startswith("- ") and line.strip().endswith(".yaml")
    }
    for path in sorted(K8S.glob("*.yaml")):
        if path.name in {"kustomization.yaml"} or path.name.endswith(".example.yaml"):
            continue
        if not any(
            doc and doc.get("kind") in {"PrometheusRule", "ServiceMonitor"}
            for doc in yaml.safe_load_all(path.read_text(encoding="utf-8"))
        ):
            continue
        assert path.name in listed, (
            f"{path.name} holds a Prometheus Operator CRD but is not listed in "
            "kustomization.yaml, so it never reaches the cluster"
        )


# --- the rules reference metrics that exist ---------------------------------


def test_every_metric_an_alert_queries_is_actually_exported() -> None:
    """The failure this exists for: an expression naming a metric this
    application never exports parses cleanly, is accepted by Prometheus, and
    evaluates to nothing forever. Nobody notices, because an alert that never
    fires looks exactly like a healthy system."""
    exported = _exposition_metric_names()
    unknown: dict[str, set[str]] = {}
    for rule in _all_rules():
        for metric in _referenced_metrics(rule["expr"]):
            # A histogram is queried as `_bucket`; the base family is exported
            # under its own name too, so accept either.
            if metric in exported or metric.removesuffix("_bucket") in exported:
                continue
            unknown.setdefault(rule["alert"], set()).add(metric)
    assert not unknown, f"alerts query metrics that are never exported: {unknown}"


# --- the label values an alert filters on are ones the code emits ------------

# A metric name can be correct and a label value still be wrong:
# `{status="unsuported"}` parses, evaluates, and matches nothing forever. The
# metrics module owns a closed vocabulary per label kind precisely so that a
# value outside it cannot be produced - which means an alert using a value
# outside it is guaranteed never to match, and that is checkable here without
# running Prometheus.
#
# Keyed by `(metric, label)`, not by label alone: `outcome` is one label on
# three metrics with three unrelated vocabularies. HTTP's is `ok`/`error`
# while an agent run's is `completed`/`abstained`/... - collapsing them would
# have rejected a correct alert.
_LABEL_KIND_BY_METRIC = {
    ("platform_agent_runs_total", "outcome"): "run_outcome",
    ("platform_agent_run_latency_seconds", "outcome"): "run_outcome",
    ("platform_agent_citation_validation_total", "status"): "citation_status",
}
# The HTTP outcome vocabulary is not in `platform_range_labels` because it
# belongs to `http_metrics`, not to this module. It is pinned here so a change
# on either side is a test failure rather than a dead alert.
HTTP_OUTCOMES = frozenset({"ok", "error"})
_METRIC_LABEL = re.compile(r"([a-zA-Z_:][a-zA-Z0-9_:]*)\{([^}]*)\}")


def test_the_failure_rate_alert_covers_every_non_ok_outcome() -> None:
    """The middleware records three non-`ok` outcomes from three different
    places: `error` (status >= 400), `exception` (no response at all) and
    `throttled` (rate limited). A rule that named only `error` would have
    reported a healthy system through a run of unhandled exceptions.

    So the rule filters on `!= "ok"`, and this drives a request of each kind
    through the real middleware and asserts every recorded value is selected by
    the rule's own filter. A fourth outcome added later is covered by the same
    test for free.
    """
    from fastapi import FastAPI
    from fastapi.testclient import TestClient
    from starlette.exceptions import HTTPException

    from observability_metrics import get_metrics, reset_default_metrics
    from platform_core.http_metrics import HttpMetricsMiddleware

    app = FastAPI()

    @app.get("/v1/ok")
    def ok() -> dict[str, str]:
        return {"ok": "yes"}

    @app.get("/v1/missing")
    def missing() -> dict[str, str]:
        # A status >= 400 is recorded as `error`; without a route that returns
        # one, the test would only ever see `ok` and `exception`.
        raise HTTPException(status_code=503, detail="unavailable")

    @app.get("/v1/boom")
    def boom() -> dict[str, str]:
        raise RuntimeError("unhandled")

    app.add_middleware(HttpMetricsMiddleware)
    client = TestClient(app, raise_server_exceptions=False)
    try:
        client.get("/v1/ok")
        client.get("/v1/missing")
        client.get("/v1/boom")
        recorded = {
            sample.labels.get("outcome")
            for metric in get_metrics().registry.collect()
            if metric.name == "platform_http_requests"
            for sample in metric.samples
            if sample.name.endswith("_total")
        }
    finally:
        reset_default_metrics()

    # The two the middleware can produce on its own. `throttled` is added by the
    # rate limiter, which is asserted separately in the rate-limit suite.
    assert "error" in recorded, f"expected a 4xx/5xx outcome, recorded {recorded}"
    assert "exception" in recorded, (
        f"an unhandled exception must be recorded, or the failure alert cannot see it. "
        f"Recorded: {recorded}"
    )

    rule = next(r for r in _all_rules() if r["alert"] == "PlatformErrorRateHigh")
    assert 'outcome!="ok"' in rule["expr"], (
        f"the rule must select every non-ok outcome, not a hand-listed subset: {rule['expr']}"
    )


def test_every_label_value_an_alert_filters_on_is_one_the_code_can_emit() -> None:
    from observability_metrics import platform_range_labels

    bad: dict[str, set[str]] = {}
    for rule in _all_rules():
        for metric, selector in _METRIC_LABEL.findall(rule["expr"]):
            for label, value in re.findall(r'(\w+)\s*=\s*"([^"]+)"', selector):
                if (metric, label) in _LABEL_KIND_BY_METRIC:
                    allowed = platform_range_labels(_LABEL_KIND_BY_METRIC[(metric, label)])
                elif metric == "platform_http_requests_total" and label == "outcome":
                    # Checked behaviourally in the test below rather than from
                    # a copied list, because the middleware computes it inline.
                    allowed = tuple(sorted(HTTP_OUTCOMES))
                else:
                    continue
                if value not in allowed:
                    bad.setdefault(rule["alert"], set()).add(f"{metric} {label}={value!r}")
    assert not bad, (
        f"alerts filter on label values the metrics module cannot emit: {bad}. "
        "These rules would evaluate to nothing forever."
    )


def test_the_citation_alert_uses_a_real_citation_status() -> None:
    """The wrong-answer runbook's primary signal depends on this one value, and
    the vocabulary was extended by the `superseded` work in a different file.
    Naming the dependency explicitly means a rename breaks a test instead of an
    alert nobody notices going quiet."""
    from observability_metrics import platform_range_labels

    rule = next(r for r in _all_rules() if r["alert"] == "PlatformCitationValidationUnsupported")
    assert 'status="unsupported"' in rule["expr"], rule["expr"]
    assert "unsupported" in platform_range_labels("citation_status")


def test_every_alert_has_a_severity_and_a_runbook_anchor() -> None:
    """A page with no severity is a page with no routing. The annotation names
    the document section that says what to do, so the runbook and the alert
    cannot drift apart silently."""
    for rule in _all_rules():
        labels = rule.get("labels", {})
        annotations = rule.get("annotations", {})
        assert labels.get("severity") in {"critical", "warning"}, rule["alert"]
        assert labels.get("component"), rule["alert"]
        assert annotations.get("summary"), rule["alert"]
        assert annotations.get("description"), rule["alert"]
        assert "runbook" in annotations, f"{rule['alert']} has no runbook anchor"


# --- the documented thresholds have a rule -----------------------------------


# Each entry: (alert name, why this one is not optional). The runbook and the
# checklist name these signals; an alert is how a threshold becomes a gate.
_REQUIRED_ALERTS = {
    # docs/launch-checklist-and-runbook.md §1.3: cost p95 <= 5 cents.
    "PlatformRunCostP95High": "cost p95 is a launch threshold with no gate",
    # docs/launch-checklist-and-runbook.md §1.3: total latency p95 < 8s.
    "PlatformRunLatencyP95High": "run latency p95 is a launch threshold with no gate",
    # An outbox row retired with no handler is a business event that went
    # nowhere, and the row is still marked sent.
    "PlatformOutboxUnhandledEvents": "a business event with no consumer is otherwise invisible",
    # Model errors mean answers are being produced by the fallback chain or not
    # at all; the runbook's first step assumes this is visible.
    "PlatformModelErrorsHigh": "model failure rate is the runbook's first diagnostic",
    # Queue age, not run latency: a backed-up queue produces a fast run and a
    # waiting customer. The metric docstring says so explicitly.
    "PlatformInboxQueueAgeHigh": "queue age is invisible in run latency",
    # A reclaimed claim is a worker that died mid-run, which means a customer
    # message was processed twice or not at all.
    "PlatformStaleClaimsReclaiming": "repeated stale claims mean workers are dying mid-run",
    # The runbook names this as the wrong-answer trigger signal.
    "PlatformCitationValidationUnsupported": "the wrong-answer runbook's primary signal",
    # Availability: the API is the only thing serving the customer surface.
    "PlatformApiDown": "no customer can reach the platform at all",
}


@pytest.mark.parametrize("alert", sorted(_REQUIRED_ALERTS))
def test_each_documented_threshold_has_an_alert(alert: str) -> None:
    names = {rule["alert"] for rule in _all_rules()}
    assert alert in names, (
        f"{alert} is missing - {_REQUIRED_ALERTS[alert]}. declared: {sorted(names)}"
    )


def test_the_availability_alert_is_not_a_no_op_expression() -> None:
    """`up == 0` is correct only if the `job` label is the one Prometheus
    actually stamps on the scraped series. A ServiceMonitor whose `job_name`
    differs from what the expression filters on makes the alert permanently
    silent, so the two are asserted against each other.

    `job_name`, not the port name: `job_name` is what Prometheus copies into the
    `job` label. Asserting the port instead would pass while the alert matched
    nothing.
    """
    down = next(r for r in _all_rules() if r["alert"] == "PlatformApiDown")
    assert "up{" in down["expr"]
    monitors = _service_monitors()
    assert monitors, "no ServiceMonitor: nothing scrapes /metrics, so no rule can ever fire"
    for monitor in monitors:
        for endpoint in monitor["spec"]["endpoints"]:
            job = endpoint.get("job_name") or monitor["metadata"]["name"]
            assert f'job="{job}"' in down["expr"], (
                f"PlatformApiDown filters on a job name the ServiceMonitor does not "
                f"produce ({job}): {down['expr']}"
            )
        for endpoint in monitor["spec"]["endpoints"]:
            # The port has to exist on the Service, or the scrape target never
            # resolves and `up` stays absent rather than 0 - which no rule here
            # can distinguish from healthy.
            assert endpoint["port"], monitor["metadata"]["name"]


def test_the_scrape_target_is_the_metrics_service_port() -> None:
    """The Service names its port `metrics` (30-api.yaml). A monitor that says
    `http` would select a port that does not exist on this Service."""
    service_ports = {
        s["metadata"]["name"]: {p["name"] for p in s["spec"]["ports"]}
        for s in [
            doc
            for path in sorted(K8S.glob("*.yaml"))
            if not path.name.endswith(".example.yaml")
            for doc in yaml.safe_load_all(path.read_text(encoding="utf-8"))
            if doc and doc.get("kind") == "Service"
        ]
    }
    assert "metrics" in service_ports.get("platform-api-metrics", set()), (
        f"platform-api-metrics ports: {service_ports.get('platform-api-metrics')}"
    )
    for monitor in _service_monitors():
        for endpoint in monitor["spec"]["endpoints"]:
            assert endpoint["port"] in service_ports.get("platform-api-metrics", set()), (
                f"{monitor['metadata']['name']} scrapes port {endpoint['port']!r}, which the "
                "Service does not expose"
            )


def test_a_service_monitor_exists_for_the_metrics_endpoint() -> None:
    """`test_metrics_are_not_routed_through_the_ingress` already asserts the
    metrics Service exists and is internal. Nothing was scraping it, so the
    39 metric families the audit measured had no consumer at all."""
    monitors = _service_monitors()
    assert monitors, "/metrics has a Service but no ServiceMonitor scrapes it"
    for monitor in monitors:
        assert monitor["spec"]["endpoints"][0]["path"] == "/metrics"
        # The namespace default, like every other object here.
        assert monitor["metadata"]["namespace"] == "b2b-support"
        # It must select the API, not match everything in the namespace and
        # scrape whatever answers 200 on /metrics.
        selector = monitor["spec"]["selector"]["matchLabels"]
        assert selector.get("app.kubernetes.io/name") == "platform", monitor["metadata"]["name"]


# --- the tracing dependency is actually installed ----------------------------


def test_the_opentelemetry_sdk_is_a_declared_runtime_dependency() -> None:
    """`observability_tracing.build_tracer` imports the OTel SDK and the OTLP
    HTTP exporter the moment `OTEL_EXPORTER_OTLP_ENDPOINT` is set, and falls
    back to an in-process ring buffer on `ImportError`. With neither package in
    `requirements.txt` that fallback is the *only* behaviour: setting the
    endpoint logs a warning and nothing is ever exported. The module is written
    to degrade safely, which is why the omission was invisible.

    This asserts the declaration, not the import, so a checkout that installs
    the declared set is guaranteed the import to succeed.
    """
    requirements = (REPO_ROOT / "requirements.txt").read_text(encoding="utf-8")
    declared = {
        line.split(">=")[0].split("==")[0].strip().lower()
        for line in requirements.splitlines()
        if line.strip() and not line.strip().startswith("#")
    }
    for package in ("opentelemetry-sdk", "opentelemetry-exporter-otlp"):
        assert package in declared, (
            f"{package} is imported by observability_tracing.build_tracer but is not in "
            "requirements.txt, so the exporter path is unreachable in every deployment"
        )


def test_the_otel_environment_is_declared_in_the_workload_manifests() -> None:
    """`OTEL_SERVICE_NAME` is what separates the API's spans from a worker's in
    the collector. Without it both are `platform`, and a trace cannot be read
    by process.

    Scoped to Deployments on purpose. The migration Job is a one-shot process
    that runs `alembic upgrade head` and exits without emitting a span, so
    naming its traces would assert something about a program that does not
    exist rather than about a real gap.

    The endpoint itself is deliberately absent: it is cluster configuration, and
    a hardcoded collector address in a manifest is a wrong value rather than a
    missing one.
    """
    for path in sorted(K8S.glob("*.yaml")):
        if path.name.endswith(".example.yaml"):
            continue
        for doc in yaml.safe_load_all(path.read_text(encoding="utf-8")):
            if not doc or doc.get("kind") != "Deployment":
                continue
            spec = doc["spec"]["template"]["spec"]
            for container in spec.get("containers", []):
                env = {e["name"]: e.get("value") for e in container.get("env", [])}
                assert "OTEL_SERVICE_NAME" in env, (
                    f"{doc['metadata']['name']}/{container['name']} emits spans with no "
                    "service name, so its traces are indistinguishable in the collector"
                )
                assert env["OTEL_SERVICE_NAME"], doc["metadata"]["name"]
                assert "OTEL_EXPORTER_OTLP_ENDPOINT" not in env, (
                    f"{doc['metadata']['name']} hardcodes the collector endpoint; it belongs "
                    "in the ConfigMap, where a cluster can change it without a new image"
                )


def test_each_deployment_names_itself_distinctly() -> None:
    """`platform` for every workload would satisfy the previous test and still
    make the collector useless. The API and the four worker roles all emit
    spans, so their service names have to be tellable apart."""
    names: dict[str, str] = {}
    for path in sorted(K8S.glob("*.yaml")):
        if path.name.endswith(".example.yaml"):
            continue
        for doc in yaml.safe_load_all(path.read_text(encoding="utf-8")):
            if not doc or doc.get("kind") != "Deployment":
                continue
            for container in doc["spec"]["template"]["spec"].get("containers", []):
                env = {e["name"]: e.get("value") for e in container.get("env", [])}
                service = env.get("OTEL_SERVICE_NAME")
                if service:
                    names[doc["metadata"]["name"]] = service
    collisions = [name for name, count in _counts(names.values()).items() if count > 1]
    assert not collisions, f"deployments share an OTEL service name: {collisions} ({names})"
    # The API and the interactive worker are the two that answer a customer;
    # they must not be the same series in the collector.
    assert names.get("platform-api") != names.get("platform-worker-interactive"), names


def _counts(values: Any) -> dict[str, int]:
    out: dict[str, int] = {}
    for value in values:
        out[value] = out.get(value, 0) + 1
    return out
