import React,{useState} from 'react';
import {Routes,Route} from 'react-router-dom';
import {SupportChat} from '@product/pages/SupportChat';
import {Workbench} from '@product/pages/Workbench';
import {ProposalPanel} from '@product/pages/Approvals';
import {usePrompt} from '@product/components/Prompt';
import {ProductContext} from '../product-context';
import {state,NOW} from '../fixtures/api';
import {resetCustomerSession} from '../fake-api';
import {shot,onDrive,onRender,frame} from '../engine';
import '@product/styles.css';
const settle=async()=>{for(let i=0;i<4;i++)await frame()};
const clickText=async(root,label)=>{const e=[...root.querySelectorAll('button')].find(e=>e.textContent.trim()===label&&!e.disabled);if(!e)throw Error('Missing clickable '+label);window.__clickPoint={x:e.getBoundingClientRect().left+e.getBoundingClientRect().width*.6,y:e.getBoundingClientRect().top+e.getBoundingClientRect().height*.6};e.click();await settle()};
function inputText(el,text){if(!el||el.value===text)return;Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,text);el.dispatchEvent(new Event('input',{bubbles:true}));}
function Background(){return <><div className="ambient"/><svg className="route-line" viewBox="0 0 1920 1080"><path d="M-80 780 H520 Q660 780 660 640 V470 Q660 360 820 360 H1980"/></svg><div className="grain"/><div className="video-cursor"><svg width="34" height="42" viewBox="0 0 34 42"><path d="M3 2 L29 25 L17 25 L12 38 Z" fill="white" stroke="#163a50" strokeWidth="2"/></svg><i/></div></>}
function Copy({s,index}){return <div className="copy"><div className="eyebrow">B2B SUPPORT <span> / {index}</span></div><h2><span className="en">{s.headlineEn}</span><span className="zh">{s.headline}</span></h2><p>{s.description}</p><div className="small-proof">真实产品组件 · 合成演示数据</div></div>}
export function Intro({shot:s}){return <><Background/><div className="intro-copy"><div className="eyebrow">ENTERPRISE AI CUSTOMER SUPPORT</div><h1><span className="en">Support.<br/>With control.</span><span className="zh">{s.headline}</span></h1><div className="intro-foot">B2B SUPPORT <i/> 企业级 AI 智能客服平台</div></div><div className="orbit-label">EVIDENCE → PEOPLE → ACTION</div></>}
export function Customer({shot:s}){const[k,set]=useState(0);window.__resetCustomer=()=>set(x=>x+1);return <><Background/><Copy s={s} index="01"/><div className="screen customer-screen"><div className="screen-top"><i/><i/><i/><span>客户入口 / SUPPORT</span></div><div className="screen-crop"><div className="customer-camera"><SupportChat key={k}/></div></div></div></>}
export function WorkbenchShot({shot:s}){const[k,set]=useState(0);window.__resetWorkbench=()=>set(x=>x+1);return <><Background/><Copy s={s} index="02"/><div className="screen workbench-screen"><div className="screen-top"><i/><i/><i/><span>坐席工作台 / WORKBENCH</span></div><div className="screen-crop"><div className="workbench-camera"><ProductContext key={k}><Routes><Route path="/admin/workbench/conversation/:conversationRef" element={<Workbench/>}/></Routes></ProductContext></div></div></div></>}
const initial={proposal_id:'film-proposal',tool_name:'case.create',tool_version:1,risk:'confirmed_write',status:'authorized',effective_status:'authorized',arguments:{category:'invoice_application',subject:'发票申请（演示）'},action_hash:'evidence-bound-demo-request-2026',permission_decision:'allow',permission_reason:'case.write.confirmed',required_confirmation:true,expires_at:NOW+1800};
function ApprovalProduct(){const[status,set]=useState('authorized');const prompt=usePrompt();return <div className="approval-stage"><ProposalPanel detail={{proposal:{...initial,status,effective_status:status},executions:status==='verified'?[{execution_id:'film-execution',status:'executed',verification_status:'verified',output:{case_ref:'DEMO-CASE-2026',scope:'平台内部申请工单'},error_code:null,started_at:NOW,completed_at:NOW}]:[]}} busy={false} onClose={()=>{}} onApprove={async()=>{if(await prompt.confirm('批准这次写操作？','批准','确认仅创建平台内部发票申请工单，不会开票。'))set('confirmed')}} onExecute={async()=>{if(await prompt.confirm('执行这次写操作？','执行','仅运行本片的合成响应演示。'))set('verified')}}/>{prompt.element}</div>}
export function ApprovalShot({shot:s}){const[k,set]=useState(0);window.__resetApproval=()=>set(x=>x+1);return <><Background/><Copy s={s} index="03"/><div className="screen approval-screen"><div className="screen-top"><i/><i/><i/><span>受控业务提案 / TOOL GATEWAY</span></div><div className="screen-crop"><div className="approval-camera"><ProductContext key={k}><ApprovalProduct/></ProductContext></div></div></div><div className="approval-note">演示：创建内部申请工单 · 不代表实际开票</div></>}
export function Close({shot:s}){return <><Background/><div className="close-copy"><div className="eyebrow">ENTERPRISE AI CUSTOMER SUPPORT</div><h2><span className="en">B2B Support</span><span className="zh">{s.headline}</span></h2><div className="principles"><span>有据回答</span><span>人工掌控</span><span>受控执行</span></div><div className="end-note">桌面网页演示 · 合成数据<br/>企业系统接入与生产放量仍需验收</div></div></>}
export function buildScene(tl,id){const s=shot(id),root=document.querySelector(`[data-shot="${id}"]`);if(id==='intro')tl.set(root,{opacity:1},0);else tl.fromTo(root,{opacity:0},{opacity:1,duration:.32,ease:'none'},s.start-.25);tl.fromTo(root.querySelector('.route-line path'),{strokeDashoffset:2600},{strokeDashoffset:0,duration:Math.min(4,s.end-s.start),ease:'power2.out'},s.start);const copy=root.querySelector('.copy,.intro-copy,.close-copy');tl.fromTo(copy,{opacity:0,y:35},{opacity:1,y:0,duration:id==='intro'?.6:.42,ease:'power3.out'},s.start+(id==='intro'?.12:-.12));const screen=root.querySelector('.screen');if(screen){tl.fromTo(screen,{opacity:0,x:id==='workbench'?120:0,y:id==='customer'?65:0,clipPath:id==='approval'?'inset(0 0 100% 0)':'inset(0 0 0% 0)'},{opacity:1,x:0,y:0,clipPath:'inset(0 0 0% 0)',duration:.48,ease:'power3.out'},s.start-.14);tl.fromTo(screen,{scale:1},{scale:1.018,duration:s.end-s.start-1.1,ease:'none'},s.start+.9);}if(id!=='close')tl.to(root,{opacity:0,duration:.16},s.end-.16);onRender(id,local=>{const cursor=root.querySelector('.video-cursor');const times=s.actions.map(a=>a.at);const nearest=times.reduce((best,t)=>Math.abs(local-t)<Math.abs(local-best)?t:best,999);const delta=local-nearest;const point=window.__clickPoint;cursor.style.opacity=point&&Math.abs(delta)<.4?'1':'0';if(point){cursor.style.transform=`translate(${point.x}px,${point.y}px)`;cursor.querySelector('i').style.transform=`scale(${1+Math.max(0,delta)*5})`;cursor.querySelector('i').style.opacity=String(Math.max(0,1-Math.max(0,delta)*3));}});
if(id==='customer'){let stage=-1;onDrive(id,async local=>{if(local<0)return;const want=local>=2.6?2:local>=1.5?1:0;if(want<stage){state.sent=false;state.answer=false;resetCustomerSession();window.__resetCustomer();await settle();stage=0;}if(stage<0){await settle();stage=0;}const ta=root.querySelector('textarea');if(want===0){const count=Math.max(0,Math.floor((local-.3)*30));inputText(ta,'请帮我确认订单 SO-DEMO-2026 的进度。'.slice(0,count));await frame();}if(want>=1&&stage<1){inputText(root.querySelector('textarea'),'请帮我确认订单 SO-DEMO-2026 的进度。');await settle();const form=root.querySelector('textarea')?.closest('form');const btn=form?.querySelector('button[type="submit"]');if(!btn)throw Error('Support send missing');window.__clickPoint={x:btn.getBoundingClientRect().left+30,y:btn.getBoundingClientRect().top+30};btn.click();await settle();stage=1;}if(want>=2&&stage<2){state.answer=true;window.__filmTick();await settle();stage=2;}if(local>=2.6){const thread=root.querySelector('.support-thread');if(thread)thread.scrollTop=Math.max(0,local-3.1)*80;}});}
if(id==='workbench'){let claimed=false;onDrive(id,async local=>{if(local<0)return;if(local<2&&claimed){state.claimed=false;window.__resetWorkbench();await settle();claimed=false;}if(local>=2&&!claimed){await clickText(root,'接入会话');claimed=true;}if(local>=4.1){inputText(root.querySelector('.wb-composer textarea'),'我已接手，将核对交付安排后继续为您跟进。'.slice(0,Math.floor((local-4.1)*24)));await frame();}});onRender(id,local=>{const camera=root.querySelector('.workbench-camera');const u=Math.min(1,Math.max(0,(local-3.2)/1.5));camera.style.transform=`translate(${-540}px,${-112-u*413}px) scale(1.7)`;});}
if(id==='approval'){let stage=0;onDrive(id,async local=>{if(local<0)return;const want=local>=4.3?4:local>=3.5?3:local>=2.4?2:local>=1.2?1:0;if(want<stage){window.__resetApproval();await settle();stage=0;}while(stage<want){if(stage===0)await clickText(root,'批准');if(stage===1)await clickText(root.querySelector('.prompt'),'批准');if(stage===2)await clickText(root,'执行');if(stage===3)await clickText(root.querySelector('.prompt'),'执行');stage++;}});onRender(id,local=>{const y=local<4.3?-120:-Math.min(370,120+(local-4.3)*260);root.querySelector('.approval-camera').style.transform=`translate(0px,${y}px) scale(1.8)`;});}
}
